config/routes.rb
Rails.application.routes.draw do

	root "welcome#index"
	
  resources :likes, only: [:create, :destroy]
  resources :statuses, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create]
  delete '/signout', to: "sessions#destroy", as: 'signout' 

end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :status
	validates :status_id, :user_id, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
	belongs_to :user
	has_many :likes, dependent: :destroy
	default_scope -> {order("created_at DESC")}
	validates :content, presence: true, length: {minimum: 10, message: "content is too short"}
	validates :title, presence: true, length: {minimum: 8, message: "title is too short"}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
	validates :password, length: { in: 6..20 }
	validates :password_confirmation, presence: true
	has_many :statuses, dependent: :destroy
	has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user 
  	return User.find(session[:user_id]) if session[:user_id]
  end

  def require_login 
  	redirect_to root_path unless session[:user_id]
  end  

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_login, only: [:create, :destroy]
  before_action :set_like, only: [:destroy]

  def create
  	if params[:like] && !liked_before
  		@like = Like.new(status_id: params[:like][:status], user_id: current_user.id) 
  	else 
  		@like = Like.new 
  	end 

  	if @like.save 
  		redirect_to(root_path, flash:{notice: "You liked #{@like.status.title}!"})
  	else
  		redirect_to(root_path, flash:{alert: "You liked before!"})
  	end 
  end

  def destroy
	@like.destroy
	flash[:notice] = "You unlike."
  	redirect_to status_path(@like.status) 
  end 

  private 
  def liked_before
  	if params[:like][:user] && params[:like][:status]
  		@user = User.find(params[:like][:user])
  		@status = Status.find(params[:like][:status])
  		@user.likes.find_by(status_id:@status.id).present?
  	end 
  end 

  def set_like
  	@like = Like.find(params[:id])
  end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

  	@user = User.find_by(email: params[:session][:email])
  	
  	if @user && @user.authenticate(params[:session][:password])
  		
  		session[:user_id] = @user.id
  		redirect_to(statuses_path, flash:{notice: "Welcome, #{@user.email}!"})
  	else 
  		flash[:alert] = "Please log in again"
  		render :new
  	end 
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:edit, :update, :destroy]

  before_action :require_login
  
  def new
    @status = Status.new
  end

  def create
    @status = current_user.statuses.new(status_params)
    if @status.save
      redirect_to(@status, flash:{notice: "Status is created successfully."})
    else 
      flash[:alert] = "Error creating status. #{@status.errors.full_messages.to_sentence}"
      render :new
    end 
  end

  def edit
  end

  def update
    @status.update(status_params)
    if @status.save
      redirect_to(@status, flash:{notice: "Status is updated successfully."})
    else 
      render :edit
    end 
  end

  def destroy
    @status.destroy
    redirect_to(statuses_path, flash:{notice: "Status is deleted." })
  end

  private 
  def status_params
    params.require(:status).permit(:title, :content)
  end 

  def set_status
    @status = Status.find(params[:id])
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      redirect_to(user_path(@user), flash:{notice: "Account created. Please log in now."}) 
    else 
      flash[:alert] = "Error creating account: #{@user.errors.full_messages.to_sentence} "
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to(@user, flash:{notice: "Account is updated successfully."})
    else 
      render :edit
    end 
  end

  def destroy
    @user.destroy 
    redirect_to(statuses_path, flash:{notice: "Account is deleted"})
  end

  private 
  def set_user
    @user = User.find(params[:id])
  end 

  def user_params 
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testing</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= yield %>

  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/statuses/create.html.erb
<h1>Statuses#create</h1>
<p>Find me in app/views/statuses/create.html.erb</p>

app/views/statuses/destroy.html.erb
<h1>Statuses#destroy</h1>
<p>Find me in app/views/statuses/destroy.html.erb</p>

app/views/statuses/edit.html.erb
<h1>Statuses#edit</h1>
<p>Find me in app/views/statuses/edit.html.erb</p>

app/views/statuses/new.html.erb
<h1>Statuses#new</h1>
<p>Find me in app/views/statuses/new.html.erb</p>

app/views/statuses/update.html.erb
<h1>Statuses#update</h1>
<p>Find me in app/views/statuses/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<%= link_to "Home", root_path %> 

<% if session[:user_id] %> 
<%= link_to "Log Out", signout_path, method: :delete %> 
<% else %> 
<%= link_to "Log In", new_session_path %> 
<% end %>